# Generated by Django 4.2.4 on 2023-08-24 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep', models.PositiveIntegerField(help_text='Sleep in minutes')),
                ('calories', models.PositiveIntegerField(help_text='Calories consumed')),
                ('stress', models.PositiveIntegerField(help_text='Stress level from 0 to 100')),
                ('steps', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField(help_text='Weight in kilograms')),
                ('wellness_score', models.PositiveIntegerField(help_text='Wellness score from 0 to 100')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_infos', to='health_app.userprofile')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
