# Generated by Django 4.2.4 on 2023-08-24 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0002_dateinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dateinfo',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
